<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['1631737520:AAElqePVcsOZumKIaHJJ2ENjetGS2TyZ0Ps'];
$BOT_NAME = $_ENV['Dost Bot'];
$BOT_USERNAME = $_ENV['mybratrobot'];

?>
